package fr.martiben.webgratinos.srv;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GratinImplService", targetNamespace = "http://srv.webgratinos.martiben.fr/", wsdlLocation = "http://localhost:9845/gratin?wsdl")
public class GratinImplService extends Service {

    private final static URL GRATINIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(fr.martiben.webgratinos.srv.GratinImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = fr.martiben.webgratinos.srv.GratinImplService.class.getResource(".");
            url = new URL(baseUrl, "http://raspi:9845/gratin?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://raspi:9845/gratin?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GRATINIMPLSERVICE_WSDL_LOCATION = url;
    }

    public GratinImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GratinImplService() {
        super(GRATINIMPLSERVICE_WSDL_LOCATION, new QName("http://srv.webgratinos.martiben.fr/", "GratinImplService"));
    }

    /**
     * 
     * @return returns GratinInterface
     */
    @WebEndpoint(name = "GratinImplPort")
    public GratinInterface getGratinImplPort() {
        return super.getPort(new QName("http://srv.webgratinos.martiben.fr/", "GratinImplPort"), GratinInterface.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default
     *            values.
     * @return returns GratinInterface
     */
    @WebEndpoint(name = "GratinImplPort")
    public GratinInterface getGratinImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://srv.webgratinos.martiben.fr/", "GratinImplPort"), GratinInterface.class, features);
    }

}
