
package fr.martiben.webgratinos.srv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "GratinInterface", targetNamespace = "http://srv.webgratinos.martiben.fr/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface GratinInterface {


    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean isGratinDispo(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void changeGratinStatus(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    boolean arg1);

}
